# Site settings
title: EconPUCP
tag_text: EconPUCP
description: Hub de recursos para la investigación económica

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
